In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import warnings
warnings.filterwarnings('ignore')

sns.set_style("whitegrid")

# 2. Numpy Part 2

## 2.1 Indexing
+ như mảng bình thường, tương tự như c++

In [3]:
a = np.array([1, 2, 3])

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
])

c = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ],
])

In [4]:
a[0:2]

array([1, 2])

In [5]:
b[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [6]:
c[0, ::, 0:2]

array([[1, 2],
       [4, 5]])

In [7]:
c[(c < 10) & (c > 2)]

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
c[(c < 4) | (c > 10)]

array([ 1,  2,  3, 11, 12])

## 2.2 np.where

In [9]:
a = np.random.randint(0, 10, size=5)

In [10]:
a

array([7, 3, 9, 0, 0])

In [11]:
# trả về index những số thỏa điều kiện 
np.where(a < 3)

(array([3, 4], dtype=int64),)

In [12]:
# thay những giá trị < 3 thành -1, ngược lại thì trả 1
np.where(a < 3, -1, 1)

array([ 1,  1,  1, -1, -1])

In [13]:
# thay những giá trị < 3 thành -1, ngược lại giữ nguyên
np.where(a < 3, -1, a)

array([ 7,  3,  9, -1, -1])

## 2.3 Transposing

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/foundations/numpy/transpose.png" width="400">
</div>

In [14]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

In [15]:
a.shape

(2, 3)

In [16]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
# 1, 0: là xoay
# 0, 1: là như cũ
a_transpose = np.transpose(a, (1, 0))

In [18]:
a_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
a_transpose.shape

(3, 2)

## 2.4 Reshaping

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/foundations/numpy/reshape.png" width="450">
</div>

In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [21]:
# tham số -1  là để nó tự tính
np.reshape(a, (3, -1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
np.reshape(a, (4, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
np.reshape(a, (3, 2, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## 2.5 Adding/removing dimensions

In [46]:
x = np.array([1, 2, 3])

In [25]:
y = np.expand_dims(x, axis = [1])

In [26]:
y.shape

(3, 1)

In [27]:
x = np.array([[1,2,3], [4,5,6]])

In [28]:
y = np.expand_dims(x, axis=[1])

In [29]:
y.shape

(2, 1, 3)

In [30]:
# Removing dimensions
y = np.squeeze(y, axis=1)

In [31]:
y.shape

(2, 3)

## 2.6 Arithmetic

In [32]:
x = np.array([
    [1, 2],
    [3, 4],
])

y = np.array([
    [5, 6],
    [7, 8],
])

In [33]:
x @ y

array([[19, 22],
       [43, 50]])

In [34]:
# x * y
np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [35]:
# x + y
np.add(x, y) 

array([[ 6,  8],
       [10, 12]])

In [36]:
# x - y
np.subtract(x, y)

array([[-4, -4],
       [-4, -4]])

### Axis operations

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/foundations/numpy/axis.gif" width="450">
</div>

In [37]:
x

array([[1, 2],
       [3, 4]])

In [38]:
np.sum(x)

10

In [39]:
np.sum(x, axis = 1)

array([3, 7])

In [40]:
np.sum(x, axis = 0)

array([4, 6])

In [41]:
np.max(x)

4

In [42]:
np.max(x, axis = 0)

array([3, 4])

In [43]:
np.max(x, axis = 1)

array([2, 4])